(()=>{
const BUILD='20260908.25';

/* One authoritative interaction layer. No sentence/quiz observers, no duplicate touch+click stacks. */
const css=document.createElement('style');css.textContent=`
/* Explore — real rendered classes, high-contrast Hanzi */
#wall .wt.ex-unseen{background:linear-gradient(135deg,#f8fafc 0%,#e7edf5 100%)!important;color:#172033!important;border-color:#d8e0ea!important;font-weight:700!important}
#wall .wt.ex-learning{background:linear-gradient(135deg,#22d3ee 0%,#818cf8 52%,#a855f7 100%)!important;color:#101827!important;border-color:rgba(16,24,39,.14)!important;font-weight:760!important;text-shadow:0 1px 0 rgba(255,255,255,.32)!important}
#wall .wt.ex-mastered{background:linear-gradient(135deg,#34d399 0%,#2dd4bf 48%,#38bdf8 100%)!important;color:#082f2b!important;border-color:rgba(8,47,43,.14)!important;font-weight:760!important;text-shadow:0 1px 0 rgba(255,255,255,.28)!important}
#wall .wt.ex-struggle{background:linear-gradient(135deg,#fb7185 0%,#ec4899 48%,#c026d3 100%)!important;color:#351020!important;border-color:rgba(53,16,32,.14)!important;font-weight:760!important;text-shadow:0 1px 0 rgba(255,255,255,.22)!important}
[data-theme=dark] #wall .wt.ex-unseen{background:linear-gradient(135deg,#262b35,#353b49)!important;color:#f8fafc!important}
[data-theme=dark] #wall .wt.ex-learning,[data-theme=dark] #wall .wt.ex-mastered,[data-theme=dark] #wall .wt.ex-struggle{color:#0b1020!important}

/* Sentence recall */
.sentenceExample{cursor:pointer;touch-action:manipulation;-webkit-tap-highlight-color:transparent}.sentenceExample .exPy,.sentenceExample .exEn{transition:filter .10s ease,opacity .10s ease}.sentenceExample.v25-hidden .exPy,.sentenceExample.v25-hidden .exEn{filter:blur(6px)!important;opacity:.34!important;user-select:none!important}.sentenceExample:not(.v25-hidden) .exPy,.sentenceExample:not(.v25-hidden) .exEn{filter:none!important;opacity:1!important}.sentenceNext{touch-action:manipulation!important}

/* Quiz */
.v25quiz .quizBody{padding-top:14px}.v25quiz button{touch-action:manipulation}.v25quiz .quizChoice.correct{background:#d8fae8!important;color:#145c46!important;outline:2px solid #7ed8b8!important}.v25quiz .quizChoice.wrong{background:#fde8ec!important;color:#8b2744!important;outline:2px solid #ef9eb4!important}.v25quiz .quizChoice.dim{opacity:.38}
.v25connect .quizBody{padding:10px 12px!important}.v25connect .tripleTitle{font-size:20px;font-weight:780}.v25connect .tripleSub{font-size:12px;color:var(--muted);margin:3px 0 8px}.v25connect .tripleGrid{display:grid;grid-template-columns:.72fr 1fr 1.25fr;gap:5px}.v25connect .tripleCol{display:flex;flex-direction:column;gap:5px}.v25connect .tripleLabel{text-align:center;font-size:9px;letter-spacing:.08em;text-transform:uppercase;color:var(--muted);font-weight:750}.v25connect .matchItem{min-height:43px;border:1px solid var(--line);background:var(--paper);border-radius:9px;padding:4px;display:grid;place-items:center;text-align:center;font-size:12px;line-height:1.12;color:var(--ink)!important;transition:background .11s ease,border-color .11s ease,box-shadow .11s ease,transform .11s ease,color .11s ease}.v25connect .matchItem.hanzi{font-family:"PingFang SC","Noto Sans CJK SC",sans-serif;font-size:25px;color:var(--ink)!important}.v25connect .matchItem.pinyin{font-size:12px;font-weight:700;color:var(--green)!important}.v25connect .matchItem.selected{background:linear-gradient(135deg,#eae5ff,#d8f4ff)!important;color:#2d245c!important;border-color:#8b7cf6!important;box-shadow:0 0 0 2px rgba(124,92,246,.13)!important;transform:translateY(-1px)}.v25connect .matchItem.hanzi.selected{color:#241b50!important}.v25connect .matchItem.pinyin.selected{color:#4c3bb5!important}.v25connect .matchItem.matched{background:linear-gradient(135deg,#d8fae8,#c8f4ee)!important;color:#145c46!important;border-color:#7ed8b8!important;opacity:1!important}.v25connect .matchItem.hanzi.matched{color:#123d32!important}.v25connect .matchItem.pinyin.matched{color:#17654e!important}.v25connect .matchItem.wrong{background:#fde8ec!important;color:#8b2744!important}.v25connect .tripleStatus{text-align:center;font-size:11px;color:var(--muted);margin-top:7px;min-height:16px}
.v25write .quizBody{justify-content:flex-start;padding-top:9px}.v25write .writePrompt{text-align:center}.v25write .writePrompt .meaning{font-size:28px;font-weight:780}.v25write .writePrompt .pinyin{font-size:17px;color:var(--green);font-weight:700;margin-top:4px}.v25write .writeCanvas{width:min(69vw,290px);aspect-ratio:1;margin:10px auto 8px;border:1px solid var(--line);border-radius:14px;background:var(--paper);position:relative;overflow:hidden;touch-action:none!important;-webkit-user-select:none;user-select:none}.v25write .writeCanvas:before,.v25write .writeCanvas:after{content:'';position:absolute;background:var(--line);opacity:.65;pointer-events:none;z-index:0}.v25write .writeCanvas:before{width:1px;height:100%;left:50%}.v25write .writeCanvas:after{height:1px;width:100%;top:50%}.v25write .writeTarget{position:absolute;inset:0;z-index:1;touch-action:none!important}.v25write .writeTarget svg{touch-action:none!important;transform:translateZ(0)}.v25write .writeActions{display:flex;justify-content:center;gap:8px}.v25write .writeActions button{min-height:40px;border:1px solid var(--line);background:var(--paper);border-radius:9px;padding:0 13px;font:inherit;font-size:12px;font-weight:700}.v25write .writeStatus{text-align:center;color:var(--muted);font-size:11px;margin-top:7px;min-height:16px}.v25write .writeCanvas.stroke-good{box-shadow:0 0 0 4px rgba(52,211,153,.22)}.v25write .writeCanvas.stroke-bad{box-shadow:0 0 0 4px rgba(251,113,133,.20)}.v25write .finishQuiz{display:none;margin:8px auto 0;min-height:40px;border:0;border-radius:9px;padding:0 18px;background:var(--ink);color:var(--bg);font-weight:750}.v25write.done .finishQuiz{display:block}
`;
document.head.appendChild(css);

function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function currentSix(){try{return focusSet.slice(0,6).filter(Boolean)}catch{return []}}
function score(c,fields,ok){if(!c)return;try{const s=sk(c.h);state.seen[c.h]=1;s.exposures=(s.exposures||0)+1;s.last=Date.now();if(ok)fields.forEach(f=>s[f]=Math.min(5,(s[f]||0)+1));else s.mistakes=(s.mistakes||0)+1;mastery(c);save();progress()}catch{}}
function distractors(c,n=3){return shuffle(ALL.filter(x=>x.h!==c.h&&x.contextMeaning!==c.contextMeaning)).slice(0,n)}

function recolorExplore(){document.querySelectorAll('#wall .wt[data-w]').forEach(el=>{const h=el.dataset.w,s=state.skills?.[h]||{};el.classList.remove('ex-unseen','ex-learning','ex-mastered','ex-struggle');if(state.mastered?.[h])el.classList.add('ex-mastered');else if((s.mistakes||0)>=2)el.classList.add('ex-struggle');else if(state.seen?.[h])el.classList.add('ex-learning');else el.classList.add('ex-unseen')})}
const wall=document.getElementById('wall');if(wall)new MutationObserver(recolorExplore).observe(wall,{childList:true});setTimeout(recolorExplore,50);
const oldProgress=window.progress;window.progress=function(){const r=oldProgress?.();recolorExplore();return r};

function bindLearnCard(fp){
 const c=byH[fp.dataset.h];if(!c)return;
 const sentence=fp.querySelector('.sentenceExample');if(sentence){sentence.classList.add('v25-hidden');sentence.onpointerup=e=>{if(e.pointerType==='touch'&&e.isPrimary===false)return;e.preventDefault();e.stopPropagation();sentence.classList.toggle('v25-hidden')};sentence.onclick=e=>{e.preventDefault();e.stopPropagation()}}
 const next=fp.querySelector('[data-next-sentence]');if(next){next.onpointerup=e=>{e.preventDefault();e.stopPropagation();const list=examples(c)||[];if(!list.length)return;const wrap=fp.querySelector('.sentenceExample'),idx=(Number(wrap.dataset.sentenceIndex||0)+1)%list.length,ex=list[idx];wrap.dataset.sentenceIndex=idx;wrap.querySelector('.exCn').textContent=ex[0]||'';wrap.querySelector('.exPy').textContent=ex[1]||'';wrap.querySelector('.exEn').textContent=ex[2]||'';wrap.classList.add('v25-hidden')};next.onclick=e=>{e.preventDefault();e.stopPropagation()}}
 const speak=fp.querySelector('[data-speak]');if(speak)speak.onclick=e=>{e.preventDefault();e.stopPropagation();speak?window.speak(c):null};
 const stroke=fp.querySelector('[data-stroke]');if(stroke)stroke.onclick=e=>{e.preventDefault();e.stopPropagation();openStroke(c)};
 fp.querySelectorAll('[data-family]').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();const r=byH[b.dataset.family];if(r)window.openFocus([r],0)});
}

function recallSlide(c,type,i){const slide=document.createElement('div');slide.className='fp quizSlide v25quiz';const opts=shuffle([c,...distractors(c)]);let prompt,hero,cls,render,fields;if(type==='meaning'){prompt='What does this character mean?';hero=c.h;cls='char';render=x=>x.contextMeaning;fields=['recognition','meaning']}else if(type==='pinyin'){prompt='Which pinyin matches this character?';hero=c.h;cls='char';render=x=>x.p;fields=['recognition','sound']}else{prompt='Which character means this?';hero=c.contextMeaning;cls='word';render=x=>x.h;fields=['recognition','meaning']}slide.innerHTML=`<div class="card"><div class="quizTop">TEST · ${i+1}/6</div><div class="quizBody"><div class="quizPrompt">${prompt}</div><div class="quizHero ${cls}">${hero}</div><div class="quizChoices">${opts.map(x=>`<button class="quizChoice ${type==='hanzi'?'charChoice':''}" data-v25-choice data-h="${x.h}" data-ok="${x.h===c.h}">${render(x)}</button>`).join('')}</div><div class="quizFeedback"><div class="feedbackChar">${c.h}</div><div class="feedbackText"><b>${c.p}</b><span>${c.contextMeaning}</span></div></div><div class="quizHint">Choose an answer</div></div></div>`;slide.querySelectorAll('[data-v25-choice]').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();if(slide.dataset.answered)return;slide.dataset.answered='1';const ok=b.dataset.ok==='true';slide.querySelectorAll('[data-v25-choice]').forEach(x=>{if(x.dataset.ok==='true')x.classList.add('correct');else if(x===b)x.classList.add('wrong');else x.classList.add('dim')});slide.querySelector('.quizFeedback').classList.add('on');slide.querySelector('.quizHint').textContent='Swipe to continue';score(c,fields,ok)});return slide}

function mixedSix(){const cur=currentSix(),ids=new Set(cur.map(c=>c.h));const recent=ALL.filter(c=>state.seen?.[c.h]&&!ids.has(c.h)).sort((a,b)=>(sk(b.h).last||0)-(sk(a.h).last||0));const old=shuffle(recent.slice(0,18)).slice(0,3),now=shuffle(cur).slice(0,3);const out=[...old,...now];for(const c of [...cur,...recent])if(out.length<6&&!out.some(x=>x.h===c.h))out.push(c);return shuffle(out.slice(0,6))}
function connectSlide(){const chosen=mixedSix();const hz=shuffle(chosen),py=shuffle(chosen),en=shuffle(chosen),slide=document.createElement('div');slide.className='fp quizSlide v25quiz v25connect';slide.innerHTML=`<div class="card"><div class="quizTop">TEST · 5/6</div><div class="quizBody"><div class="tripleTitle">Connect the three</div><div class="tripleSub">Match 6 Hanzi — recent + earlier characters.</div><div class="tripleGrid"><div class="tripleCol"><div class="tripleLabel">Hanzi</div>${hz.map(c=>`<button class="matchItem hanzi" data-h="${c.h}" data-k="h">${c.h}</button>`).join('')}</div><div class="tripleCol"><div class="tripleLabel">Pinyin</div>${py.map(c=>`<button class="matchItem pinyin" data-h="${c.h}" data-k="p">${c.p}</button>`).join('')}</div><div class="tripleCol"><div class="tripleLabel">Meaning</div>${en.map(c=>`<button class="matchItem" data-h="${c.h}" data-k="m">${c.contextMeaning||''}</button>`).join('')}</div></div><div class="tripleStatus">Tap one item in each column</div></div></div>`;let sel={};const status=slide.querySelector('.tripleStatus');slide.onclick=e=>{const b=e.target.closest('.matchItem');if(!b||b.classList.contains('matched'))return;e.preventDefault();e.stopPropagation();slide.querySelectorAll(`.matchItem[data-k="${b.dataset.k}"]`).forEach(x=>x.classList.remove('selected'));b.classList.add('selected');sel[b.dataset.k]=b;if(!(sel.h&&sel.p&&sel.m))return;const a=[sel.h,sel.p,sel.m],ok=a.every(x=>x.dataset.h===a[0].dataset.h);if(ok){a.forEach(x=>{x.classList.remove('selected');x.classList.add('matched')});score(chosen.find(x=>x.h===a[0].dataset.h),['recognition','sound','meaning'],true);sel={};if(!slide.querySelector('.matchItem:not(.matched)')){slide.dataset.answered='1';status.textContent='All 6 connected ✓ · swipe to continue'}else status.textContent='Correct — keep going'}else{a.forEach(x=>{x.classList.add('wrong');setTimeout(()=>x.classList.remove('wrong','selected'),180)});sel={};status.textContent='Not quite — try again'}};return slide}

function writingSlide(c){const slide=document.createElement('div');slide.className='fp quizSlide v25quiz v25write';slide.innerHTML=`<div class="card"><div class="quizTop">TEST · 6/6</div><div class="quizBody"><div class="writePrompt"><div class="meaning">${c.contextMeaning||''}</div><div class="pinyin">${c.p||''}</div></div><div class="writeCanvas"><div class="writeTarget"></div></div><div class="writeActions"><button type="button" data-model>Show model</button><button type="button" data-restart>Start over</button></div><div class="writeStatus">Write the character from memory in the correct stroke order.</div><button type="button" class="finishQuiz">Finish quiz</button></div></div>`;const box=slide.querySelector('.writeCanvas'),target=slide.querySelector('.writeTarget'),status=slide.querySelector('.writeStatus'),modelBtn=slide.querySelector('[data-model]');let model=false,w=null;['touchstart','touchmove','touchend','pointerdown','pointermove','pointerup'].forEach(t=>box.addEventListener(t,e=>{e.stopPropagation();if(t==='touchmove')e.preventDefault()},{passive:false}));const pulse=ok=>{box.classList.remove('stroke-good','stroke-bad');void box.offsetWidth;box.classList.add(ok?'stroke-good':'stroke-bad');setTimeout(()=>box.classList.remove('stroke-good','stroke-bad'),120)};function start(){target.innerHTML='';slide.classList.remove('done');if(typeof HanziWriter==='undefined'){status.textContent='Stroke practice needs internet the first time it loads.';return}const z=Math.floor(box.clientWidth);if(!z){requestAnimationFrame(start);return}w=HanziWriter.create(target,c.h,{width:z,height:z,padding:24,showOutline:model,showCharacter:false,drawingWidth:22,drawingFadeDuration:0,strokeAnimationSpeed:4,delayBetweenStrokes:0});status.textContent=model?'Model visible — follow the correct order.':'Write the character from memory in the correct stroke order.';w.quiz({showHintAfterMisses:2,highlightOnComplete:false,onCorrectStroke:d=>{pulse(true);status.textContent=d.strokesRemaining?`✓ ${d.strokesRemaining} stroke${d.strokesRemaining===1?'':'s'} left`:'Finishing…'},onMistake:()=>{pulse(false);status.textContent='Not quite — try that stroke again'},onComplete:()=>{slide.dataset.answered='1';slide.classList.add('done');status.textContent='Character complete ✓';score(c,['writing'],true)}})}modelBtn.onclick=e=>{e.preventDefault();e.stopPropagation();model=!model;modelBtn.textContent=model?'Hide model':'Show model';start()};slide.querySelector('[data-restart]').onclick=e=>{e.preventDefault();e.stopPropagation();start()};slide.querySelector('.finishQuiz').onclick=e=>{e.preventDefault();e.stopPropagation();closeFocus();nextBoard()};slide._start=start;return slide}

function buildQuiz(set){if(set.length<6)return[];const order=shuffle(set.slice(0,6)),slides=[recallSlide(order[0],'meaning',0),recallSlide(order[1],'hanzi',1),recallSlide(order[2],'pinyin',2),recallSlide(order[3],'meaning',3),connectSlide(),writingSlide(order[4])];return slides}

window.openFocus=function(set,start=0){
 focusSet=[...set];focusSwipes=0;focusLastIndex=start;document.getElementById('quizNudge')?.classList.remove('on');const p=document.getElementById('pager');p.innerHTML='';focusSet.forEach((c,i)=>{const holder=document.createElement('div');holder.innerHTML=page(c,i);const fp=holder.firstElementChild;p.appendChild(fp);bindLearnCard(fp)});const quizSlides=focusSet.length>=6?buildQuiz(focusSet):[];quizSlides.forEach(s=>p.appendChild(s));document.getElementById('focus')?.classList.add('on');let last=-1;p.onscroll=()=>{const i=Math.round(p.scrollLeft/p.clientWidth);if(i<focusSet.length&&i!==last){last=i;focusLastIndex=i;visit(i)}else if(i>=focusSet.length){const q=i-focusSet.length+1;document.getElementById('count').textContent=`Test ${Math.min(q,6)} of 6`;const ws=quizSlides[5];if(i===focusSet.length+5&&ws&&!ws.dataset.started){ws.dataset.started='1';ws._start?.()}}};requestAnimationFrame(()=>{p.scrollLeft=p.clientWidth*start;visit(start)});
};

const vr=document.querySelector('#settingsSheet .versionRow b');if(vr)vr.textContent='v '+BUILD;window.__hanziBuild=BUILD;
})();