/* HANZI CONSOLIDATED CONTROLLER
   Version: CONSOLIDATED 2.3.0 — CONFIRMED LESSON PROGRESSION
   Branch: clean-consolidation
   Contract: one owner for 6-card lesson paging, focus swipes, quiz flow and writing.
*/
(()=>{
'use strict';
const VERSION='CONSOLIDATED 2.3.0';
const LESSON_SIZE=12,PAGE_SIZE=6;
const S=()=>window.HanziStore;
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const now=()=>performance.now();
function unique(list){const out=[],seen=new Set();for(const c of list||[])if(c?.h&&!seen.has(c.h)){seen.add(c.h);out.push(c)}return out}
function shuffled(list){const a=[...(list||[])];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function all(){return S().ALL||[]}
function char(h){return S().byH?.[h]}
function state(){return S().state}

const BASE={
'一':['我有一个朋友。','wǒ yǒu yí ge péngyou','I have a friend.'],'人':['这里人很多。','zhèlǐ rén hěn duō','There are many people here.'],'大':['北京很大。','Běijīng hěn dà','Beijing is very big.'],'小':['这个房间很小。','zhège fángjiān hěn xiǎo','This room is small.'],'我':['我是学生。','wǒ shì xuésheng','I am a student.'],'你':['你好吗？','nǐ hǎo ma','How are you?'],'好':['今天天气很好。','jīntiān tiānqì hěn hǎo','The weather is very nice today.'],'是':['他是老师。','tā shì lǎoshī','He is a teacher.'],'不':['我不喝咖啡。','wǒ bù hē kāfēi','I don’t drink coffee.'],'有':['我有一个问题。','wǒ yǒu yí ge wèntí','I have a question.'],'在':['我在家。','wǒ zài jiā','I am at home.'],'学':['我在学汉语。','wǒ zài xué Hànyǔ','I am learning Chinese.'],'吃':['我们去吃饭吧。','wǒmen qù chīfàn ba','Let’s go eat.'],'喝':['我想喝水。','wǒ xiǎng hē shuǐ','I want to drink water.'],'看':['我晚上看书。','wǒ wǎnshang kàn shū','I read in the evening.'],'说':['你会说汉语吗？','nǐ huì shuō Hànyǔ ma','Can you speak Chinese?'],'想':['我想去中国。','wǒ xiǎng qù Zhōngguó','I want to go to China.'],'去':['明天我去北京。','míngtiān wǒ qù Běijīng','Tomorrow I’m going to Beijing.'],'来':['你什么时候来？','nǐ shénme shíhou lái','When are you coming?'],'水':['请给我一杯水。','qǐng gěi wǒ yì bēi shuǐ','Please give me a glass of water.']};
const CURATED={'呢':[['你呢？','nǐ ne','And you?'],['你在做什么呢？','nǐ zài zuò shénme ne','What are you doing?']],'吗':[['你好吗？','nǐ hǎo ma','How are you?'],['你喜欢喝茶吗？','nǐ xǐhuan hē chá ma','Do you like drinking tea?']],'吧':[['我们走吧。','wǒmen zǒu ba','Let’s go.'],['你先坐吧。','nǐ xiān zuò ba','Have a seat first.']],'得':[['他说得很快。','tā shuō de hěn kuài','He speaks very quickly.'],['你做得很好。','nǐ zuò de hěn hǎo','You did very well.']],'地':[['他慢慢地走。','tā mànmàn de zǒu','He walks slowly.']],'过':[['我去过北京。','wǒ qù guo Běijīng','I have been to Beijing.'],['你吃过这个吗？','nǐ chī guo zhège ma','Have you eaten this before?']],'着':[['门开着。','mén kāi zhe','The door is open.'],['他坐着看书。','tā zuò zhe kàn shū','He is reading while sitting.']],'给':[['请给我一杯水。','qǐng gěi wǒ yì bēi shuǐ','Please give me a glass of water.'],['我给你打电话。','wǒ gěi nǐ dǎ diànhuà','I’ll call you.']],'从':[['我从巴黎来。','wǒ cóng Bālí lái','I come from Paris.'],['从这里走。','cóng zhèlǐ zǒu','Go from here.']],'到':[['我八点到公司。','wǒ bā diǎn dào gōngsī','I get to the office at eight.'],['你什么时候到？','nǐ shénme shíhou dào','When will you arrive?']],'对':[['你说得对。','nǐ shuō de duì','You are right.'],['这个对我很重要。','zhège duì wǒ hěn zhòngyào','This is very important to me.']],'比':[['他比我高。','tā bǐ wǒ gāo','He is taller than me.'],['今天比昨天冷。','jīntiān bǐ zuótiān lěng','Today is colder than yesterday.']],'还':[['我还没吃饭。','wǒ hái méi chīfàn','I haven’t eaten yet.'],['他还在工作。','tā hái zài gōngzuò','He is still working.']],'又':[['他又来了。','tā yòu lái le','He came again.']],'最':[['这个最好。','zhège zuì hǎo','This one is the best.']]};
const MEM={'好':'女 + 子. Use the two clear halves as the hook: woman + child → “good”. This is a mnemonic, not a literal modern definition.','休':'亻 + 木: picture a person leaning against a tree to rest.','明':'日 + 月: sun + moon → two bright things → “bright”.','看':'手 above 目: picture shading your eyes with your hand to look.','问':'门 around 口: a mouth at the door asking a question.','妈':'女 gives the meaning family; 马 mainly gives the sound clue.','吗':'口 signals speech/question; 马 supplies the sound.','想':'相 above 心. 心 is the strong memory anchor: thinking happens in the mind.','家':'宀 is the roof/home clue. The lower part is historically 豕 (pig), a useful visual fact but not a modern definition.','人':'Originally a pictograph of a standing person seen from the side.','山':'An ancient pictograph of mountain peaks; the silhouette is still visible.','口':'A pictograph of an open mouth; it often appears in speaking/mouth-related characters.','日':'Originally a drawing of the sun. It also means “day” and appears in time-related characters.','月':'Originally a moon pictograph. As a component it can also represent 肉 “flesh”, so context matters.','木':'A tree pictograph: trunk, branches and roots. It recurs widely in plant/wood characters.','女':'An ancient pictograph of a kneeling woman. Use the modern shape as the visual anchor.','子':'An ancient pictograph of a child; it appears as both a word and a component.'};
function memory(c){if(MEM[c.h])return MEM[c.h];if(c.component_note&&!c.component_note.includes('Start with the whole silhouette'))return c.component_note;if(c.keyContext)return c.keyContext;return c.context&&c.context!==c.h?c.context:`Remember the silhouette first: ${c.h}.`}
function sentenceFallbacks(c){const pool=[[`今天我学“${c.h}”。`,`jīntiān wǒ xué “${c.p}”.`,`Today I’m learning ${c.h}.`],[`你认识“${c.h}”吗？`,`nǐ rènshi “${c.p}” ma?`,`Do you recognize ${c.h}?`],[`老师写了“${c.h}”。`,`lǎoshī xiě le “${c.p}”.`,`The teacher wrote ${c.h}.`],[`我记得“${c.h}”。`,`wǒ jìde “${c.p}”.`,`I remember ${c.h}.`]];const k=(Number(c.index)||c.h.codePointAt(0)||0)%pool.length;return[...pool.slice(k),...pool.slice(0,k)]}
function goodSentence(ex,c){const zh=(ex?.[0]||'').trim();return!!zh&&zh.includes(c.h)&&zh.length>1}
function lessonNumberFor(c){const idx=Math.max(1,Number(c.index)||all().findIndex(x=>x.h===c.h)+1);return Math.max(1,Math.ceil(idx/LESSON_SIZE))}
function sentenceScore(ex,c,bias=0){const allowed=new Set(all().slice(0,lessonNumberFor(c)*LESSON_SIZE).map(x=>x.h)),zh=(ex?.[0]||'').trim();let han=0,unknown=0;for(const ch of zh){if(/[\u3400-\u9fff]/.test(ch)){han++;if(ch!==c.h&&!allowed.has(ch))unknown++}}const pyWords=(ex?.[1]||'').trim().split(/\s+/).filter(Boolean).length;return unknown*120+han*4+pyWords+bias}
function examples(c){const candidates=[],seen=new Set();const add=(ex,bias=0)=>{if(!goodSentence(ex,c)||seen.has(ex[0]))return;seen.add(ex[0]);candidates.push({ex,bias})};if(CURATED[c.h])CURATED[c.h].forEach(ex=>add(ex,0));if(BASE[c.h])add(BASE[c.h],0);if(goodSentence([c.context],c)&&/[。！？?!]$/.test((c.context||'').trim()))add([c.context,c.contextPinyin||'',c.contextMeaning||''],4);for(const x of all())if(x!==c&&goodSentence([x.context],c)&&/[。！？?!]$/.test((x.context||'').trim()))add([x.context,x.contextPinyin||'',x.contextMeaning||''],12);candidates.sort((a,b)=>sentenceScore(a.ex,c,a.bias)-sentenceScore(b.ex,c,b.bias));const out=candidates.slice(0,3).map(x=>x.ex);for(const ex of sentenceFallbacks(c))if(out.length<3&&!out.some(x=>x[0]===ex[0]))out.push(ex);return out.slice(0,3)}
function related(c){const raw=c.relatedShapes||c.related||c.family||c.similar||[],out=[];for(const r of Array.isArray(raw)?raw:[]){const x=typeof r==='string'?char(r):r;if(x?.h&&x.h!==c.h&&!out.some(y=>y.h===x.h))out.push(x)}return out.slice(0,4)}

function ensureProgressionState(){const st=state();st.confirmed=st.confirmed||{};st.lessonPassed=st.lessonPassed||{};st.lessonCheckpoints=st.lessonCheckpoints||{};for(const [h,s] of Object.entries(st.skills||{}))if((s?.recognition||0)>0)st.confirmed[h]=1;if(!Number.isFinite(Number(st.currentLesson))||Number(st.currentLesson)<1)st.currentLesson=1;S().save()}
function confirmCharacter(c){if(!c)return;state().confirmed=state().confirmed||{};if(!state().confirmed[c.h]){state().confirmed[c.h]=1;S().save()}}
function lessonInfo(){const a=all(),totalLessons=Math.max(1,Math.ceil(a.length/LESSON_SIZE)),current=clamp(Number(state().currentLesson||1),1,totalLessons),chars=a.slice((current-1)*LESSON_SIZE,current*LESSON_SIZE),mastered=chars.filter(c=>state().mastered?.[c.h]).length,confirmed=chars.filter(c=>state().confirmed?.[c.h]).length,completedLessons=Object.values(state().lessonPassed||{}).filter(Boolean).length;return{current,totalLessons,chars,mastered,confirmed,total:chars.length,completedLessons}}
function lessonChars(){return lessonInfo().chars}
function checkpointFor(lesson=lessonInfo().current){state().lessonCheckpoints=state().lessonCheckpoints||{};return Number(state().lessonCheckpoints[lesson]||0)}
function setCheckpoint(lesson,n){state().lessonCheckpoints=state().lessonCheckpoints||{};state().lessonCheckpoints[lesson]=Math.max(Number(state().lessonCheckpoints[lesson]||0),n);S().save()}
function phaseLabel(lesson=lessonInfo().current){const cp=checkpointFor(lesson);return cp===0?'Set 1 of 2':cp===1?'Set 2 of 2':'Review'}
function updateContinueLabel(){const b=q('#continue');if(!b)return;const info=lessonInfo(),cp=checkpointFor(info.current),left=Math.max(0,info.total-info.confirmed);b.textContent=cp===0?'Learn first 6':cp===1?'Learn next 6':left?`Review lesson · ${left} to confirm`:'Review lesson'}
function tileState(c){const sk=S().skill(c.h);if(state().mastered?.[c.h])return'MASTERED';if(state().seen?.[c.h])return(sk.mistakes||0)>1?'REVIEW':'LEARNING';return'NEW'}
function renderLessonProgress(){const info=lessonInfo(),confirmedPct=info.total?Math.round(info.confirmed/info.total*100):0;q('#pLabel').textContent=`Lesson ${info.current} · ${phaseLabel(info.current)}`;q('#pCount').textContent=`${info.confirmed}/${info.total} confirmed`;q('#pBar').style.width=confirmedPct+'%';let card=q('#progressScreen .lessonProgressCard');if(!card){card=document.createElement('div');card.className='map lessonProgressCard';const map=q('#progressScreen .map');map?.insertAdjacentElement('beforebegin',card)}if(card)card.innerHTML=`<div class="lessonRow"><div><span class="lessonEyebrow">CURRENT LESSON</span><b>Lesson ${info.current} of ${info.totalLessons}</b></div><strong>${info.confirmed}/${info.total}</strong></div><div class="lessonMiniBar"><i style="width:${confirmedPct}%"></i></div><div class="lessonMeta">${phaseLabel(info.current)} · ${info.completedLessons} lesson${info.completedLessons===1?'':'s'} completed · ${info.mastered}/${info.total} mastered long-term</div>`;updateContinueLabel()}
function progress(){const a=all(),m=a.filter(c=>state().mastered?.[c.h]).length,se=a.filter(c=>state().seen?.[c.h]).length,l=a.filter(c=>state().seen?.[c.h]&&!state().mastered?.[c.h]).length,p=a.length?Math.round(m/a.length*100):0;q('#mStat').textContent=m;q('#lStat').textContent=l;q('#sStat').textContent=se;q('#pctStat').textContent=p+'%';q('#mapBar').style.width=p+'%';renderLessonProgress();refreshTileStates();if(q('#exploreScreen').classList.contains('on'))renderExplore()}

let lessonPage=0,boardGesture=null,boardSuppressUntil=0;
function pages(){const x=lessonChars();return[x.slice(0,6),x.slice(6,12)].filter(x=>x.length)}
function makeTile(c,set,i){const b=document.createElement('button');b.className='tile';b.dataset.h=c.h;const tag=tileState(c);b.classList.toggle('review',tag==='REVIEW');b.innerHTML=`<span class="tag">${tag}</span><span class="hz">${c.h}</span>${state().seen?.[c.h]?'<i class="dot"></i>':''}`;b.onclick=e=>{e.preventDefault();e.stopPropagation();if(now()<boardSuppressUntil)return;openFocus(set,i)};return b}
function renderBoard(page=lessonPage){const p=pages();if(!p.length)return;lessonPage=clamp(page,0,p.length-1);q('#board').replaceChildren(...p[lessonPage].map((c,i)=>makeTile(c,p[lessonPage],i)));q('#lessonDots').innerHTML=p.map((_,i)=>`<i class="${i===lessonPage?'on':''}"></i>`).join('')}
function refreshTileStates(){qa('#board .tile').forEach(b=>{const c=char(b.dataset.h);if(!c)return;const tag=tileState(c);b.querySelector('.tag').textContent=tag;b.classList.toggle('review',tag==='REVIEW');let d=b.querySelector('.dot');if(state().seen?.[c.h]&&!d){d=document.createElement('i');d.className='dot';b.appendChild(d)}else if(!state().seen?.[c.h]&&d)d.remove()})}
function installBoardSwipe(){const board=q('#board');board.addEventListener('click',e=>{if(now()<boardSuppressUntil){e.preventDefault();e.stopImmediatePropagation()}},true);board.onpointerdown=e=>{if(e.button!=null&&e.button!==0)return;boardGesture={id:e.pointerId,x:e.clientX,y:e.clientY,axis:null,drag:false}};board.onpointermove=e=>{const g=boardGesture;if(!g||g.id!==e.pointerId)return;const dx=e.clientX-g.x,dy=e.clientY-g.y,ax=Math.abs(dx),ay=Math.abs(dy);if(!g.axis){if(ax<10&&ay<10)return;if(ax>ay*1.2){g.axis='x';try{board.setPointerCapture(e.pointerId)}catch{}}else{g.axis='y';return}}if(g.axis==='x'){g.drag=true;e.preventDefault()}};board.onpointerup=e=>{const g=boardGesture;boardGesture=null;if(!g||g.id!==e.pointerId||!g.drag)return;boardSuppressUntil=now()+350;const dx=e.clientX-g.x;if(dx<-55&&lessonPage<pages().length-1)renderBoard(lessonPage+1);else if(dx>55&&lessonPage>0)renderBoard(lessonPage-1);e.preventDefault()};board.onpointercancel=()=>boardGesture=null}
function weakness(c){const s=S().skill(c.h);return(state().mastered?.[c.h]?-100:0)+(s.mistakes||0)*8+(5-(s.recognition||0))*2+(5-(s.meaning||0))*2+(5-(s.sound||0))}
function reviewPick(lesson,lessonNumber){state().lessonMissed=state().lessonMissed||{};const unconfirmed=lesson.filter(c=>!state().confirmed?.[c.h]),missed=(state().lessonMissed[lessonNumber]||[]).map(char).filter(c=>c&&lesson.some(x=>x.h===c.h)),rest=[...lesson].filter(c=>!unconfirmed.some(x=>x.h===c.h)&&!missed.some(x=>x.h===c.h)).sort((a,b)=>weakness(b)-weakness(a));return unique([...unconfirmed,...missed,...rest]).slice(0,6)}
function continueLearning(){const info=lessonInfo(),cp=checkpointFor(info.current);if(cp===0){lessonPage=0;renderBoard(0);openFocus(info.chars.slice(0,6),0,'set1');return}if(cp===1){lessonPage=1;renderBoard(1);openFocus(info.chars.slice(6,12),0,'set2');return}const pick=reviewPick(info.chars,info.current);if(pick.length)openFocus(pick,0,'review')}

let focusSet=[],slides=[],active=0,learnCount=0,gesture=null,suppressUntil=0,settleTimer=null,sessionMissed=new Set(),sessionLesson=0,sessionKind='review';
const speakerIcon='<svg aria-hidden="true" viewBox="0 0 24 24" fill="none"><path d="M5 9v6h4l5 4V5L9 9H5Z" stroke="currentColor" stroke-width="1.8" stroke-linejoin="round"/><path d="M17 9.5c1.4 1.4 1.4 3.6 0 5" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/><path d="M19.5 7c2.8 2.8 2.8 7.2 0 10" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg>';
function learnSlide(c){const ex=examples(c),rel=related(c),s=document.createElement('div');s.className='fp';s.dataset.h=c.h;s.innerHTML=`<div class="card"><div class="cHead">HSK 1 · ${c.index||''}/${all().length}</div><div class="heroChar"><div class="big">${c.h}</div><div class="mainRecall hidden"><div class="py">${c.p||''}</div><div class="meaning">${c.contextMeaning||''}</div></div><button class="audio" data-audio aria-label="Play pronunciation">${speakerIcon}</button></div><div class="learnBody"><div class="section"><div class="lab">KEY CONTEXT</div><div class="memory">${memory(c)}</div></div><div class="section"><div class="lab">IN A SENTENCE</div><div class="sentenceExample hidden" data-i="0"><div class="exCn">${ex[0][0]}</div><div class="exPy">${ex[0][1]}</div><div class="exEn">${ex[0][2]}</div></div><div class="sentenceTools"><button class="sentenceCycle" data-next aria-label="Next sentence" title="Next sentence">↻</button></div></div><div class="section"><div class="lab">RELATED SHAPES</div>${rel.length?`<div class="relatedList">${rel.map(r=>`<button data-related="${r.h}"><span class="rh">${r.h}</span><span class="rp">${r.p||''}</span><span class="rm">${r.contextMeaning||''}</span></button>`).join('')}</div>`:'<div class="none">Related forms will appear when available.</div>'}</div><button class="stroke" data-practice>✍️ Practice stroke order</button></div></div>`;const recall=s.querySelector('.mainRecall');recall.onclick=e=>{e.preventDefault();e.stopPropagation();recall.classList.toggle('hidden')};const sent=s.querySelector('.sentenceExample');sent.onclick=e=>{e.preventDefault();e.stopPropagation();sent.classList.toggle('hidden')};s.querySelector('[data-next]').onclick=e=>{e.preventDefault();e.stopPropagation();const i=(+sent.dataset.i+1)%ex.length;sent.dataset.i=i;sent.querySelector('.exCn').textContent=ex[i][0];sent.querySelector('.exPy').textContent=ex[i][1];sent.querySelector('.exEn').textContent=ex[i][2];sent.classList.add('hidden')};s.querySelector('[data-audio]').onclick=e=>{e.preventDefault();e.stopPropagation();S().speak(c)};s.querySelector('[data-practice]').onclick=e=>{e.preventDefault();e.stopPropagation();openPractice(c)};s.querySelectorAll('[data-related]').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();const r=char(b.dataset.related);if(r)openFocus([r],0)});return s}
function distractors(c,n=3){return shuffled(all().filter(x=>x.h!==c.h&&x.contextMeaning!==c.contextMeaning)).slice(0,n)}
function recallQuiz(c,type,n){const s=document.createElement('div');s.className='fp';const opts=shuffled([c,...distractors(c)]);let prompt,hero,render,fields,heroClass='char';if(type==='meaning'){prompt='What does this character mean?';hero=c.h;render=x=>x.contextMeaning;fields=['recognition','meaning']}else if(type==='pinyin'){prompt='Which pinyin matches this character?';hero=c.h;render=x=>x.p;fields=['recognition','sound']}else{prompt='Which character means this?';hero=c.contextMeaning;render=x=>x.h;fields=['recognition','meaning'];heroClass='word'}s.innerHTML=`<div class="card"><div class="quizTop">TEST · ${n}/6</div><div class="quizBody"><div class="quizPrompt">${prompt}</div><div class="quizHero ${heroClass}">${hero||''}</div><div class="quizChoices">${opts.map(x=>`<button class="quizChoice ${type==='hanzi'?'charChoice':''}" data-h="${x.h}">${render(x)||''}</button>`).join('')}</div><div class="quizFeedback"><div class="feedbackChar">${c.h}</div><div class="feedbackText"><b>${c.p||''}</b><span>${c.contextMeaning||''}</span></div></div><div class="quizHint">Choose an answer</div></div></div>`;s.querySelectorAll('.quizChoice').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();if(s.dataset.answered)return;s.dataset.answered='1';const ok=b.dataset.h===c.h;if(!ok)sessionMissed.add(c.h);else confirmCharacter(c);s.querySelectorAll('.quizChoice').forEach(x=>{if(x.dataset.h===c.h)x.classList.add('correct');else if(x===b)x.classList.add('wrong');else x.classList.add('dim')});s.querySelector('.quizFeedback').classList.add('on');s.querySelector('.quizHint').textContent='Swipe to continue';S().mark(c,fields,ok)});return s}
function connectSet(set){const cur=unique(set);if(sessionKind==='set1'||sessionKind==='set2')return cur.slice(0,6);const ids=new Set(cur.map(c=>c.h)),recent=all().filter(c=>state().seen?.[c.h]&&!ids.has(c.h)).sort((a,b)=>(S().skill(b.h).last||0)-(S().skill(a.h).last||0)),out=[];for(const c of [...shuffled(recent.slice(0,18)).slice(0,3),...shuffled(cur),...recent,...all()])if(out.length<6&&!out.some(x=>x.h===c.h))out.push(c);return out.slice(0,6)}
function connectQuiz(set){const chosen=connectSet(set),s=document.createElement('div');s.className='fp';const hz=shuffled(chosen),py=shuffled(chosen),en=shuffled(chosen),sub=(sessionKind==='set1'||sessionKind==='set2')?'Match these 6 lesson characters.':'Match 6 Hanzi — recent + earlier characters.';s.innerHTML=`<div class="card"><div class="quizTop">TEST · 5/6</div><div class="quizBody"><div class="connectTitle">Connect the three</div><div class="connectSub">${sub}</div><div class="connectGrid"><div class="connectCol"><div class="connectLabel">Hanzi</div>${hz.map(c=>`<button class="matchItem hanzi" data-k="h" data-h="${c.h}">${c.h}</button>`).join('')}</div><div class="connectCol"><div class="connectLabel">Pinyin</div>${py.map(c=>`<button class="matchItem pinyin" data-k="p" data-h="${c.h}">${c.p||''}</button>`).join('')}</div><div class="connectCol"><div class="connectLabel">Meaning</div>${en.map(c=>`<button class="matchItem" data-k="m" data-h="${c.h}">${c.contextMeaning||''}</button>`).join('')}</div></div><div class="connectStatus">Tap one item in each column</div></div></div>`;let sel={};s.onclick=e=>{const b=e.target.closest('.matchItem');if(!b||b.classList.contains('matched'))return;e.preventDefault();e.stopPropagation();s.querySelectorAll(`.matchItem[data-k="${b.dataset.k}"]`).forEach(x=>x.classList.remove('selected'));b.classList.add('selected');sel[b.dataset.k]=b;if(!(sel.h&&sel.p&&sel.m))return;const trio=[sel.h,sel.p,sel.m],ok=trio.every(x=>x.dataset.h===trio[0].dataset.h),status=s.querySelector('.connectStatus');if(ok){trio.forEach(x=>{x.classList.remove('selected');x.classList.add('matched')});const matched=char(trio[0].dataset.h);confirmCharacter(matched);S().mark(matched,['recognition','sound','meaning'],true);sel={};status.textContent=s.querySelector('.matchItem:not(.matched)')?'Correct — keep going':'All 6 connected ✓ · swipe to continue'}else{trio.forEach(x=>{x.classList.add('wrong');setTimeout(()=>x.classList.remove('wrong','selected'),170)});sel={};status.textContent='Not quite — try again'}};return s}

function createWriter(target,status,c,{drawingWidth=32,outline=true,onComplete}={}){target.innerHTML='';if(typeof HanziWriter==='undefined'){status.textContent='Stroke data unavailable.';return null}const box=target.parentElement,z=Math.max(240,Math.floor(box.getBoundingClientRect().width||300));status.textContent='Loading stroke practice…';const writer=HanziWriter.create(target,c.h,{width:z,height:z,padding:24,showOutline:outline,showCharacter:false,onLoadCharDataSuccess:()=>status.textContent='Start with the first stroke.',onLoadCharDataError:()=>status.textContent='Could not load stroke data.'});writer.quiz({showHintAfterMisses:1,highlightOnComplete:true,drawingWidth,leniency:1.15,onCorrectStroke:d=>{status.textContent=d.strokesRemaining?`${d.strokesRemaining} stroke${d.strokesRemaining===1?'':'s'} left`:'Finishing…'},onMistake:()=>status.textContent='Not quite — try that stroke again',onComplete:()=>{status.textContent='Character complete ✓';S().mark(c,['writing'],true);onComplete?.()}});return writer}
let practiceChar=null,practiceWriter=null,practiceGesture=null;
function openPractice(c){practiceChar=c;q('#strokeHz').textContent=c.h;q('#strokePy').textContent=`${c.p||''} · ${c.contextMeaning||''}`;q('#strokePane').classList.add('on');requestAnimationFrame(()=>practiceWriter=createWriter(q('#target'),q('#strokeStatus'),c,{drawingWidth:32,outline:true}))}
function closePractice(){q('#strokePane').classList.remove('on');q('#target').innerHTML='';practiceGesture=null}
function watchPractice(){if(!practiceChar)return;const t=q('#target'),box=t.parentElement;t.innerHTML='';const z=Math.max(240,Math.floor(box.getBoundingClientRect().width||300));q('#strokeStatus').textContent='Watching…';practiceWriter=HanziWriter.create(t,practiceChar.h,{width:z,height:z,padding:24,showOutline:true,showCharacter:true});practiceWriter.animateCharacter({onComplete:()=>q('#strokeStatus').textContent='Tap Start over to practice.'})}
function installPracticeSwipe(){const pane=q('#strokePane');pane.onpointerdown=e=>{if(e.button!=null&&e.button!==0)return;if(e.target.closest('.canvas')){practiceGesture={blocked:true,id:e.pointerId};return}practiceGesture={id:e.pointerId,x:e.clientX,y:e.clientY,axis:null,drag:false}};pane.onpointermove=e=>{const g=practiceGesture;if(!g||g.blocked||g.id!==e.pointerId)return;const dx=e.clientX-g.x,dy=e.clientY-g.y,ax=Math.abs(dx),ay=Math.abs(dy);if(!g.axis){if(ax<9&&ay<9)return;if(ay>ax*1.15&&dy>0){g.axis='y';g.drag=true;try{pane.setPointerCapture(e.pointerId)}catch{}}else{g.axis='other';return}}if(g.axis==='y')e.preventDefault()};pane.onpointerup=e=>{const g=practiceGesture;practiceGesture=null;if(!g||g.blocked||g.id!==e.pointerId||!g.drag)return;const dy=e.clientY-g.y,dx=e.clientX-g.x;if(dy>80&&Math.abs(dy)>Math.abs(dx)*1.2){e.preventDefault();closePractice()}};pane.onpointercancel=()=>practiceGesture=null}

function sameSet(a,b){if(a.length!==b.length)return false;const ids=new Set(a.map(c=>c.h));return b.every(c=>ids.has(c.h))}
function classifySession(clean,info){if(clean.length!==6)return'review';if(sameSet(clean,info.chars.slice(0,6)))return'set1';if(sameSet(clean,info.chars.slice(6,12)))return'set2';return'review'}
function completeSession(){state().lessonMissed=state().lessonMissed||{};const prior=state().lessonMissed[sessionLesson]||[];state().lessonMissed[sessionLesson]=[...new Set([...prior,...sessionMissed])];state().lastQuizMistakes=[...sessionMissed];state().lastQuizCompletedAt=Date.now();if(sessionKind==='set1')setCheckpoint(sessionLesson,1);else if(sessionKind==='set2'&&checkpointFor(sessionLesson)>=1)setCheckpoint(sessionLesson,2);let advanced=false;if(sessionKind==='review'){const info=lessonInfo(),confirmed=info.chars.filter(c=>state().confirmed?.[c.h]).length;if(info.current===sessionLesson&&confirmed===info.total){state().lessonPassed=state().lessonPassed||{};state().lessonPassed[sessionLesson]=1;if(sessionLesson<info.totalLessons)state().currentLesson=sessionLesson+1;advanced=true}}S().save();closeFocus();if(advanced&&Number(state().currentLesson)>sessionLesson){lessonPage=0;renderBoard(0)}else if(sessionKind==='set1'&&checkpointFor(sessionLesson)>=1){lessonPage=1;renderBoard(1)}else renderBoard(lessonPage);progress()}
function writingQuiz(c){const s=document.createElement('div');s.className='fp';s.innerHTML=`<div class="card"><div class="quizTop">TEST · 6/6</div><div class="quizBody writeBody"><div class="practicePrompt">Write <b>${c.h}</b> in stroke order</div><div class="writeSurface"><div class="writeTarget"></div></div><div class="writeStatus">Loading stroke practice…</div><button class="finishQuiz">Finish quiz</button></div></div>`;s._start=()=>createWriter(s.querySelector('.writeTarget'),s.querySelector('.writeStatus'),c,{drawingWidth:32,outline:true,onComplete:()=>s.dataset.answered='1'});s.querySelector('.finishQuiz').onclick=e=>{e.preventDefault();e.stopPropagation();completeSession()};return s}
function quizSlides(set){if(set.length!==6)return[];const o=shuffled(set);return[recallQuiz(o[0],'meaning',1),recallQuiz(o[1],'hanzi',2),recallQuiz(o[2],'pinyin',3),recallQuiz(o[3],'meaning',4),connectQuiz(set),writingQuiz(o[4])]}
function openFocus(set,start=0,kind=null){const clean=unique(set).slice(0,6);if(!clean.length)return;const info=lessonInfo();focusSet=clean;sessionMissed=new Set();sessionLesson=info.current;sessionKind=kind||classifySession(clean,info);learnCount=clean.length;active=clamp(start,0,learnCount-1);slides=[...clean.map(learnSlide),...quizSlides(clean)];const track=document.createElement('div');track.className='focusTrack';slides.forEach(s=>track.appendChild(s));q('#pager').replaceChildren(track);q('#pager')._track=track;q('#focus').classList.add('on');q('#focus').setAttribute('aria-hidden','false');position(0,false);announce()}
function position(px=0,animate=false){const p=q('#pager'),t=p._track;if(!t)return;p.classList.toggle('settling',animate);t.style.transform=`translate3d(calc(${-active*100}% + ${px}px),0,0)`}
function announce(){if(active<learnCount){q('#count').textContent=`${active+1} of ${learnCount}`;S().expose(focusSet[active])}else{const n=active-learnCount+1;q('#count').textContent=`Test ${n} of 6`;if(n===6){const s=slides[active];if(s&&!s.dataset.started){s.dataset.started='1';requestAnimationFrame(()=>requestAnimationFrame(()=>s._start?.()))}}}}
function settle(to,v=0){active=clamp(to,0,slides.length-1);const ms=clamp(270-Math.abs(v)*55,215,305),p=q('#pager');p.style.setProperty('--settle',ms+'ms');position(0,true);clearTimeout(settleTimer);settleTimer=setTimeout(()=>p.classList.remove('settling'),ms+25);announce()}
function installFocusSwipe(){const p=q('#pager');p.addEventListener('click',e=>{if(now()<suppressUntil){e.preventDefault();e.stopImmediatePropagation()}},true);p.onpointerdown=e=>{if(e.button!=null&&e.button!==0)return;if(e.target.closest('button,input,.writeSurface,.writeTarget')){gesture={blocked:true,id:e.pointerId};return}gesture={id:e.pointerId,x:e.clientX,y:e.clientY,lastX:e.clientX,lastT:now(),vx:0,axis:null,drag:false}};p.onpointermove=e=>{const g=gesture;if(!g||g.blocked||g.id!==e.pointerId)return;const dx=e.clientX-g.x,dy=e.clientY-g.y,ax=Math.abs(dx),ay=Math.abs(dy);if(!g.axis){if(ax<7&&ay<7)return;if(ax>ay*1.12){g.axis='x';try{p.setPointerCapture(e.pointerId)}catch{}}else if(ay>ax*1.16){g.axis='y'}else return}if(g.axis==='y'){if(dy>0)e.preventDefault();return}g.drag=true;const t=now(),dt=Math.max(1,t-g.lastT);g.vx=.72*g.vx+.28*((e.clientX-g.lastX)/dt);g.lastX=e.clientX;g.lastT=t;let move=dx;if((active===0&&dx>0)||(active===slides.length-1&&dx<0))move=Math.sign(dx)*Math.min(20,Math.abs(dx)*.1);position(move,false);e.preventDefault()};p.onpointerup=e=>{const g=gesture;gesture=null;if(!g||g.id!==e.pointerId||g.blocked)return;const dx=e.clientX-g.x,dy=e.clientY-g.y;if(g.axis==='y'){if(dy>80&&Math.abs(dy)>Math.abs(dx)*1.25)closeFocus();return}if(!g.drag)return;suppressUntil=now()+360;const w=p.clientWidth||innerWidth,proj=dx+g.vx*120;let to=active;if(proj<-w*.16&&active<slides.length-1)to++;else if(proj>w*.16&&active>0)to--;e.preventDefault();settle(to,g.vx)};p.onpointercancel=()=>{gesture=null;settle(active)}}
function closeFocus(){q('#focus').classList.remove('on');q('#focus').setAttribute('aria-hidden','true');gesture=null;clearTimeout(settleTimer)}

let filter='all';
function exploreClass(c){if(state().mastered?.[c.h])return'ex-mastered';if((S().skill(c.h).mistakes||0)>=2)return'ex-struggle';if(state().seen?.[c.h])return'ex-learning';return'ex-unseen'}
function filterMatch(c){if(filter==='all')return true;if(filter==='struggle')return!state().mastered?.[c.h]&&(S().skill(c.h).mistakes||0)>=2;return S().level(c)===filter}
function renderExplore(){const term=(q('#search').value||'').trim().toLowerCase(),x=all().filter(c=>filterMatch(c)&&(!term||c.h.includes(term)||(c.p||'').toLowerCase().includes(term)||(c.contextMeaning||'').toLowerCase().includes(term)));q('#wall').innerHTML=x.map(c=>`<button class="wt ${exploreClass(c)}" data-h="${c.h}">${c.h}</button>`).join('');qa('#wall .wt').forEach(b=>b.onclick=()=>openFocus([char(b.dataset.h)],0))}
function showScreen(name){qa('.screen').forEach(s=>s.classList.toggle('on',s.id===name+'Screen'));qa('.nav button').forEach(b=>b.classList.toggle('on',b.dataset.screen===name));if(name==='progress')progress();if(name==='explore')renderExplore()}
function updateSettingsUI(){qa('[data-theme]').forEach(b=>b.classList.toggle('on',b.dataset.theme===state().theme));qa('[data-audio]').forEach(b=>b.classList.toggle('on',(b.dataset.audio==='on')===state().audio));q('#buildVersion').textContent=VERSION}
function openSettings(){updateSettingsUI();q('#settingsSheet').classList.add('on')}
function diagnostics(){const issues=[],board=q('#board');if(!board)issues.push('missing board');if(q('#mix'))issues.push('legacy New mix present');if(board&&pages()[lessonPage]?.length===6&&board.children.length!==6)issues.push(`board child count ${board.children.length}`);if(q('#pager')?.querySelectorAll(':scope > .focusTrack').length>1)issues.push('multiple focus tracks');window.HanziDiagnostics={version:VERSION,issues,lessonPage,lessonSize:lessonChars().length,phase:phaseLabel(),confirmed:lessonInfo().confirmed,run:diagnostics};if(issues.length)console.error('[Hanzi consolidated diagnostics]',issues)}
async function init(){try{await S().loadDataset()}catch(e){document.body.innerHTML=`<div style="font-family:system-ui;padding:32px">Could not load Hanzi dataset.<br><small>${String(e)}</small></div>`;return}ensureProgressionState();S().applyTheme();q('#buildVersion').textContent=VERSION;renderBoard(0);installBoardSwipe();installFocusSwipe();installPracticeSwipe();progress();renderExplore();q('#continue').onclick=continueLearning;q('#close').onclick=closeFocus;q('#settings').onclick=q('#fMenu').onclick=openSettings;q('#doneSettings').onclick=()=>q('#settingsSheet').classList.remove('on');qa('[data-theme]').forEach(b=>b.onclick=()=>{state().theme=b.dataset.theme;S().save();S().applyTheme();updateSettingsUI()});qa('[data-audio]').forEach(b=>b.onclick=()=>{state().audio=b.dataset.audio==='on';S().save();updateSettingsUI()});qa('.nav button').forEach(b=>b.onclick=()=>showScreen(b.dataset.screen));qa('.chip').forEach(b=>b.onclick=()=>{qa('.chip').forEach(x=>x.classList.toggle('on',x===b));filter=b.dataset.filter;renderExplore()});q('#search').oninput=renderExplore;q('#closeStroke').onclick=closePractice;q('#retry').onclick=()=>practiceChar&&(practiceWriter=createWriter(q('#target'),q('#strokeStatus'),practiceChar,{drawingWidth:32,outline:true}));q('#watch').onclick=watchPractice;window.addEventListener('hanzi:state',progress);setTimeout(diagnostics,0)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();