(()=>{
const BUILD='20260908.37';
const s=document.createElement('style');s.textContent=`
#pager.focusPager{position:relative!important;display:block!important;overflow:hidden!important;scroll-snap-type:none!important;touch-action:none!important;overscroll-behavior:none!important}
#pager.focusPager>.focusTrack{height:100%;width:100%;display:flex!important;will-change:transform;backface-visibility:hidden}
#pager.focusPager>.focusTrack>.fp{position:relative!important;inset:auto!important;flex:0 0 100%!important;width:100%!important;min-width:100%!important;height:100%!important;transform:none!important;transition:none!important}
#pager.focusPager.settling>.focusTrack{transition:transform var(--focus-settle,.28s) cubic-bezier(.22,1,.36,1)!important}
.heroChar .mainRecall,.mainRecall,.mainRecall:not(.main-hidden){background:transparent!important;box-shadow:none!important;border:0!important;border-radius:0!important;padding:0!important;min-width:0!important}.sentenceExample{background:transparent!important;box-shadow:none!important}.mainRecall{display:flex;flex-direction:column;align-items:center;cursor:pointer;-webkit-tap-highlight-color:transparent}.mainRecall .py,.mainRecall .meaning{transition:filter .1s ease,opacity .1s ease}.mainRecall.main-hidden .py,.mainRecall.main-hidden .meaning{filter:blur(7px)!important;opacity:.30!important;user-select:none!important}.mainRecall:not(.main-hidden) .py,.mainRecall:not(.main-hidden) .meaning{filter:none!important;opacity:1!important}
.writeCanvas,.embeddedCanvas,.writeTarget,.embeddedTarget,.writeTarget svg,.embeddedTarget svg{touch-action:none!important;-webkit-user-select:none!important;user-select:none!important}`;document.head.appendChild(s);
function recall(slide){if(!slide?.matches?.('.fp[data-h]'))return;const hero=slide.querySelector('.heroChar'),py=hero?.querySelector(':scope > .py'),meaning=hero?.querySelector(':scope > .meaning');if(!hero||!py||!meaning||hero.querySelector('.mainRecall'))return;const r=document.createElement('div');r.className='mainRecall main-hidden';hero.insertBefore(r,py);r.append(py,meaning);r.onclick=e=>{e.preventDefault();e.stopPropagation();r.classList.toggle('main-hidden')}}
function protectWriting(root){root.querySelectorAll('.writeCanvas,.embeddedCanvas').forEach(box=>{if(box.dataset.focusProtected)return;box.dataset.focusProtected='1';['pointerdown','pointermove','pointerup','pointercancel','touchstart','touchmove','touchend','touchcancel'].forEach(type=>box.addEventListener(type,e=>e.stopPropagation(),{passive:true}))})}
function install(p,start,learn){if(!p)return;for(const sel of [':scope > .focusTrack',':scope > .v28track']){const old=p.querySelector(sel);if(old){while(old.firstChild)p.insertBefore(old.firstChild,old);old.remove()}}const slides=[...p.children].filter(x=>x.classList?.contains('fp'));if(!slides.length)return;slides.forEach(recall);protectWriting(p);const track=document.createElement('div');track.className='focusTrack';slides.forEach(x=>track.appendChild(x));p.appendChild(track);p.className='pager focusPager';p.onscroll=null;p.scrollLeft=0;let active=Math.max(0,Math.min(start,Math.max(0,learn-1))),g=null,timer=null,suppress=0;const W=()=>p.getBoundingClientRect().width||innerWidth;function pos(px=0,anim=false){p.classList.toggle('settling',anim);track.style.transform=`translate3d(calc(${-active*100}% + ${px}px),0,0)`}function announce(){if(active<learn){window.focusLastIndex=active;try{visit(active)}catch{}}else{const c=document.getElementById('count');if(c)c.textContent=`Test ${Math.min(active-learn+1,6)} of 6`}}function settle(to,v=0){active=Math.max(0,Math.min(to,slides.length-1));const ms=Math.max(220,Math.min(320,285-Math.abs(v)*70));p.style.setProperty('--focus-settle',ms+'ms');pos(0,true);clearTimeout(timer);timer=setTimeout(()=>p.classList.remove('settling'),ms+24);announce()}
if(p._focusCap)p.removeEventListener('click',p._focusCap,true);p._focusCap=e=>{if(performance.now()<suppress){e.preventDefault();e.stopImmediatePropagation()}};p.addEventListener('click',p._focusCap,true);
p.onpointerdown=e=>{if(e.button!=null&&e.button!==0)return;if(e.target.closest('input,.writeCanvas,.embeddedCanvas,.writeTarget,.embeddedTarget')){g={blocked:true,id:e.pointerId};return}g={id:e.pointerId,x:e.clientX,y:e.clientY,lastX:e.clientX,lastT:performance.now(),vx:0,axis:null,drag:false}};
p.onpointermove=e=>{if(!g||g.blocked||g.id!==e.pointerId)return;const dx=e.clientX-g.x,dy=e.clientY-g.y,ax=Math.abs(dx),ay=Math.abs(dy);if(!g.axis){if(ax<7&&ay<7)return;if(ax>ay*1.12)g.axis='x';else if(ay>ax*1.16){g.axis='y';g.blocked=true;return}else return}if(g.axis!=='x')return;if(!g.drag){g.drag=true;p.classList.remove('settling');try{p.setPointerCapture(e.pointerId)}catch{}}const now=performance.now(),dt=Math.max(1,now-g.lastT),iv=(e.clientX-g.lastX)/dt;g.vx=g.vx*.72+iv*.28;g.lastX=e.clientX;g.lastT=now;let move=dx;if((active===0&&dx>0)||(active===slides.length-1&&dx<0))move=Math.sign(dx)*Math.min(20,Math.abs(dx)*.10);pos(move,false);e.preventDefault()};
p.onpointerup=e=>{if(!g||g.id!==e.pointerId){g=null;return}const x=g;g=null;if(x.blocked||!x.drag)return;suppress=performance.now()+380;const dx=e.clientX-x.x,w=W(),proj=dx+x.vx*120;let to=active;if(proj<-w*.16&&active<slides.length-1)to=active+1;else if(proj>w*.16&&active>0)to=active-1;e.preventDefault();settle(to,x.vx)};p.onpointercancel=()=>{g=null;settle(active,0)};pos(0,false);announce()}
const prev=window.openFocus;window.openFocus=function(set,start=0){const clean=[];for(const c of(set||[]))if(c&&!clean.some(x=>x.h===c.h))clean.push(c);const safeStart=Math.max(0,Math.min(start,Math.max(0,clean.length-1)));const out=prev(clean,safeStart);const learn=clean.length;requestAnimationFrame(()=>requestAnimationFrame(()=>{const p=document.getElementById('pager');if(p)install(p,safeStart,learn)}));return out};const vr=document.querySelector('#settingsSheet .versionRow b');if(vr)vr.textContent='v '+BUILD;window.__hanziBuild=BUILD})();