(()=>{
const BUILD='20260908.39',LESSON=12;
const css=document.createElement('style');css.textContent=`
#mix{display:none!important}.foot{height:48px!important}.foot #continue{width:100%!important;flex:1!important;font-size:14px!important}
#board.lessonDeck{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;grid-template-rows:repeat(3,minmax(0,1fr))!important;gap:8px!important;overflow:hidden!important;touch-action:none!important;position:relative!important;width:100%!important;max-width:100%!important;min-width:100%!important;transform:none!important}
#board.lessonDeck>.tile{width:100%!important;height:100%!important;min-width:0!important;min-height:0!important;margin:0!important}
.lessonDeckDots{height:15px;display:flex;justify-content:center;align-items:center;gap:6px}.lessonDeckDots i{width:5px;height:5px;border-radius:50%;background:var(--line)}.lessonDeckDots i.on{width:14px;border-radius:9px;background:var(--ink)}
.v26connect .quizBody{padding:12px 14px 8px!important}.v26connect .tripleTitle{font-size:23px!important}.v26connect .tripleSub{font-size:13px!important;margin:5px 0 13px!important}.v26connect .tripleGrid{gap:9px!important;grid-template-columns:.72fr 1fr 1.28fr!important}.v26connect .tripleCol{gap:9px!important}.v26connect .matchItem{min-height:50px!important;font-size:13px!important}.v26connect .matchItem.hanzi{font-size:29px!important}.v26connect .matchItem.pinyin{font-size:14px!important}`;document.head.appendChild(css);
function lessonChars(){let n=0;for(let i=0;i<ALL.length;i+=LESSON){const a=ALL.slice(i,i+LESSON);if(!a.every(c=>state.mastered?.[c.h])){n=i;break}n=i}return ALL.slice(n,n+LESSON)}
function makeTile(c,set,idx){const b=document.createElement('button');b.className='tile';b.dataset.h=c.h;const s=state.skills?.[c.h]||{};let tag='NEW';if(state.mastered?.[c.h])tag='MASTERED';else if(state.seen?.[c.h])tag=(s.mistakes||0)>1?'REVIEW':'LEARNING';b.innerHTML=`<span class="tag">${tag}</span><span class="hz">${c.h}</span>${state.seen?.[c.h]?'<i class="dot"></i>':''}`;b.onclick=e=>{e.preventDefault();e.stopPropagation();openFocus(set,idx)};return b}
function renderPage(board,pages,active,dots){board.dataset.lessonPage=String(active);board.replaceChildren(...pages[active].map((c,i)=>makeTile(c,pages[active],i)));[...dots.children].forEach((d,i)=>d.classList.toggle('on',i===active))}
function renderLessonDeck(forcePage){const board=document.getElementById('board');if(!board)return;const chars=lessonChars(),pages=[chars.slice(0,6),chars.slice(6,12)].filter(x=>x.length);let active=Math.max(0,Math.min(Number.isInteger(forcePage)?forcePage:Number(board.dataset.lessonPage||0),pages.length-1));board.className='board lessonDeck';let dots=board.parentElement.querySelector('.lessonDeckDots');if(!dots){dots=document.createElement('div');dots.className='lessonDeckDots';board.insertAdjacentElement('afterend',dots)}dots.innerHTML=pages.map((_,i)=>`<i class="${i===active?'on':''}"></i>`).join('');renderPage(board,pages,active,dots);let g=null,suppress=0;board.addEventListener('click',e=>{if(performance.now()<suppress){e.preventDefault();e.stopImmediatePropagation()}},true);board.onpointerdown=e=>{g={id:e.pointerId,x:e.clientX,y:e.clientY,drag:false}};board.onpointermove=e=>{if(!g||g.id!==e.pointerId)return;const dx=e.clientX-g.x,dy=e.clientY-g.y;if(!g.drag&&Math.abs(dx)>12&&Math.abs(dx)>Math.abs(dy)*1.2){g.drag=true;try{board.setPointerCapture(e.pointerId)}catch{}}if(g.drag)e.preventDefault()};board.onpointerup=e=>{if(!g||g.id!==e.pointerId)return;const x=g;g=null;if(!x.drag)return;suppress=performance.now()+300;const dx=e.clientX-x.x;let next=active;if(dx<-55&&active<pages.length-1)next=active+1;else if(dx>55&&active>0)next=active-1;if(next!==active){active=next;renderPage(board,pages,active,dots)}e.preventDefault()};board.onpointercancel=()=>{g=null}}
function refreshTileStates(){const board=document.getElementById('board');if(!board?.classList.contains('lessonDeck'))return;board.querySelectorAll('.tile[data-h]').forEach(b=>{const h=b.dataset.h,s=state.skills?.[h]||{};let tag='NEW';if(state.mastered?.[h])tag='MASTERED';else if(state.seen?.[h])tag=(s.mistakes||0)>1?'REVIEW':'LEARNING';const t=b.querySelector('.tag');if(t)t.textContent=tag;let dot=b.querySelector('.dot');if(state.seen?.[h]&&!dot){dot=document.createElement('i');dot.className='dot';b.appendChild(dot)}else if(!state.seen?.[h]&&dot)dot.remove()})}
const oldExamples=window.examples;const fallback=c=>[[`我在学“${c.h}”这个字。`,`wǒ zài xué “${c.p}” zhège zì.`,`I’m learning the character ${c.h}.`],[`你认识“${c.h}”这个字吗？`,`nǐ rènshi “${c.p}” zhège zì ma?`,`Do you recognize the character ${c.h}?`],[`老师写了“${c.h}”这个字。`,`lǎoshī xiě le “${c.p}” zhège zì.`,`The teacher wrote the character ${c.h}.`]];window.examples=function(c){let a=[];try{a=(oldExamples?.(c)||[]).filter(x=>x?.[0]?.includes(c.h))}catch{}const out=[],seen=new Set();for(const x of [...a,...fallback(c)]){if(!x?.[0]||seen.has(x[0]))continue;seen.add(x[0]);out.push(x);if(out.length===3)break}return out};
const oldOpen=window.openFocus;window.openFocus=function(set,start=0){const uniq=[];for(const c of(set||[]))if(c&&!uniq.some(x=>x.h===c.h))uniq.push(c);return oldOpen(uniq,Math.max(0,Math.min(start,uniq.length-1)))};
const cont=document.getElementById('continue');if(cont){cont.textContent='Continue learning';cont.onclick=e=>{e.preventDefault();const lesson=lessonChars(),unseen=lesson.filter(c=>!state.seen?.[c.h]),learning=lesson.filter(c=>state.seen?.[c.h]&&!state.mastered?.[c.h]),mastered=lesson.filter(c=>state.mastered?.[c.h]),pick=[];for(const c of unseen.slice(0,3))if(!pick.some(x=>x.h===c.h))pick.push(c);for(const c of [...learning,...unseen.slice(3),...mastered])if(pick.length<6&&!pick.some(x=>x.h===c.h))pick.push(c);if(pick.length)openFocus(pick.slice(0,6),0)}}document.getElementById('mix')?.remove();const oldProgress=window.progress;window.progress=function(){const r=oldProgress?.();refreshTileStates();return r};setTimeout(()=>renderLessonDeck(0),180);const vr=document.querySelector('#settingsSheet .versionRow b');if(vr)vr.textContent='v '+BUILD;window.__hanziBuild=BUILD})();