(()=>{
const BUILD='20260908.36',LESSON=12;
const css=document.createElement('style');css.textContent=`
#mix{display:none!important}.foot{height:48px!important}.foot #continue{width:100%!important;flex:1!important;font-size:14px!important}
#board.lessonDeck{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;grid-template-rows:repeat(3,minmax(0,1fr))!important;gap:8px!important;overflow:hidden!important;touch-action:none!important;transform:translate3d(0,0,0);will-change:transform}
#board.lessonDeck>.tile{width:100%!important;height:100%!important;min-width:0!important;min-height:0!important}
.lessonDeckDots{height:15px;display:flex;justify-content:center;align-items:center;gap:6px}.lessonDeckDots i{width:5px;height:5px;border-radius:50%;background:var(--line)}.lessonDeckDots i.on{width:14px;border-radius:9px;background:var(--ink)}
.v26connect .quizBody{padding:12px 14px 8px!important}.v26connect .tripleTitle{font-size:23px!important}.v26connect .tripleSub{font-size:13px!important;margin:5px 0 13px!important}.v26connect .tripleGrid{gap:9px!important;grid-template-columns:.72fr 1fr 1.28fr!important}.v26connect .tripleCol{gap:9px!important}.v26connect .tripleLabel{font-size:10px!important;margin-bottom:2px}.v26connect .matchItem{min-height:50px!important;padding:6px!important;font-size:13px!important;line-height:1.15!important}.v26connect .matchItem.hanzi{font-size:29px!important}.v26connect .matchItem.pinyin{font-size:14px!important}.v26connect .tripleStatus{font-size:12px!important;margin-top:10px!important}`;document.head.appendChild(css);
function lessonChars(){let n=0;try{for(let i=0;i<ALL.length;i+=LESSON){const a=ALL.slice(i,i+LESSON);if(!a.every(c=>state.mastered?.[c.h])){n=i;break}n=i}return ALL.slice(n,n+LESSON)}catch{return[]}}
function tile(c){const b=document.createElement('button');b.className='tile';b.dataset.h=c.h;const s=state.skills?.[c.h]||{};let tag='NEW';if(state.mastered?.[c.h])tag='MASTERED';else if(state.seen?.[c.h])tag=(s.mistakes||0)>1?'REVIEW':'LEARNING';b.innerHTML=`<span class="tag">${tag}</span><span class="hz">${c.h}</span>${state.seen?.[c.h]?'<i class="dot"></i>':''}`;b.onclick=()=>openFocus([c],0);return b}
function renderLessonDeck(forcePage){const board=document.getElementById('board');if(!board)return;const chars=lessonChars();if(!chars.length)return;const pages=[chars.slice(0,6),chars.slice(6,12)];let active=Number.isInteger(forcePage)?Math.max(0,Math.min(forcePage,pages[1].length?1:0)):Number(board.dataset.lessonPage||0);if(active===1&&!pages[1].length)active=0;board.dataset.lessonPage=String(active);board.className='board lessonDeck';board.style.transition='none';board.style.transform='translate3d(0,0,0)';board.replaceChildren(...pages[active].map(tile));let dots=board.parentElement.querySelector('.lessonDeckDots');if(!dots){dots=document.createElement('div');dots.className='lessonDeckDots';board.insertAdjacentElement('afterend',dots)}dots.innerHTML=pages[1].length?`<i class="${active===0?'on':''}"></i><i class="${active===1?'on':''}"></i>`:'<i class="on"></i>';let g=null,suppress=0;board.onclick=e=>{if(performance.now()<suppress){e.preventDefault();e.stopImmediatePropagation()}};board.onpointerdown=e=>{g={id:e.pointerId,x:e.clientX,y:e.clientY,drag:false}};board.onpointermove=e=>{if(!g||g.id!==e.pointerId)return;const dx=e.clientX-g.x,dy=e.clientY-g.y;if(!g.drag&&Math.abs(dx)>9&&Math.abs(dx)>Math.abs(dy)*1.2){g.drag=true;try{board.setPointerCapture(e.pointerId)}catch{}}if(g.drag){const edge=(active===0&&dx>0)||(active===1&&dx<0);const move=edge?Math.sign(dx)*Math.min(16,Math.abs(dx)*.10):Math.max(-54,Math.min(54,dx*.22));board.style.transition='none';board.style.transform=`translate3d(${move}px,0,0)`;e.preventDefault()}};board.onpointerup=e=>{if(!g||g.id!==e.pointerId)return;const x=g;g=null;if(!x.drag)return;suppress=performance.now()+300;const dx=e.clientX-x.x;let next=active;if(dx<-50&&active===0&&pages[1].length)next=1;else if(dx>50&&active===1)next=0;board.style.transition='transform .14s ease-out';board.style.transform='translate3d(0,0,0)';if(next!==active)setTimeout(()=>renderLessonDeck(next),145);e.preventDefault()};board.onpointercancel=()=>{g=null;board.style.transition='transform .14s ease-out';board.style.transform='translate3d(0,0,0)'}}
const oldExamples=window.examples;const fallback=c=>[[`我在学“${c.h}”这个字。`,`wǒ zài xué “${c.p}” zhège zì.`,`I’m learning the character ${c.h}.`],[`你认识“${c.h}”这个字吗？`,`nǐ rènshi “${c.p}” zhège zì ma?`,`Do you recognize the character ${c.h}?`],[`老师写了“${c.h}”这个字。`,`lǎoshī xiě le “${c.p}” zhège zì.`,`The teacher wrote the character ${c.h}.`]];window.examples=function(c){let a=[];try{a=(oldExamples?.(c)||[]).filter(x=>x&&x[0]&&x[0].includes(c.h))}catch{}const seen=new Set(),out=[];for(const x of [...a,...fallback(c)]){if(!x?.[0]||seen.has(x[0]))continue;seen.add(x[0]);out.push(x);if(out.length===3)break}return out};
const oldOpen=window.openFocus;window.openFocus=function(set,start=0){const uniq=[];for(const c of(set||[]))if(c&&!uniq.some(x=>x.h===c.h))uniq.push(c);return oldOpen(uniq,start)};
const cont=document.getElementById('continue');if(cont){cont.textContent='Continue learning';cont.onclick=e=>{e.preventDefault();const lesson=lessonChars(),unseen=lesson.filter(c=>!state.seen?.[c.h]),learning=lesson.filter(c=>state.seen?.[c.h]&&!state.mastered?.[c.h]),mastered=lesson.filter(c=>state.mastered?.[c.h]),pick=[];for(const c of unseen.slice(0,3))if(!pick.some(x=>x.h===c.h))pick.push(c);for(const c of [...learning,...unseen.slice(3),...mastered])if(pick.length<6&&!pick.some(x=>x.h===c.h))pick.push(c);if(pick.length)openFocus(pick.slice(0,6),0)}}const mix=document.getElementById('mix');if(mix)mix.remove();const oldProgress=window.progress;window.progress=function(){const r=oldProgress?.();renderLessonDeck();return r};setTimeout(()=>renderLessonDeck(0),180);const vr=document.querySelector('#settingsSheet .versionRow b');if(vr)vr.textContent='v '+BUILD;window.__hanziBuild=BUILD})();