(()=>{
const BUILD='20260908.1';
const css=`
.buildTag{position:fixed;right:8px;bottom:calc(70px + env(safe-area-inset-bottom));z-index:10;font-size:9px;color:var(--muted);opacity:.45}
.family{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:9px!important}.family button{min-width:0!important;min-height:72px!important;height:auto!important;padding:8px 10px!important;display:grid!important;grid-template-columns:auto 1fr!important;grid-template-rows:auto auto!important;column-gap:9px!important;text-align:left!important;border-radius:10px!important}.fh{grid-row:1/3;font-family:"Songti SC",serif;font-size:40px;line-height:1}.fpinyin{font-size:15px;font-weight:700;color:var(--green)}.fmeaning{font-size:13px;color:var(--muted);line-height:1.2}.sentenceHead{display:flex;align-items:center;justify-content:space-between;margin-bottom:7px}.sentenceHead .lab{margin:0}.sentenceNext{width:36px;height:36px;border:1px solid var(--line);background:var(--paper);border-radius:8px;font-size:18px}.stroke{margin-top:auto!important;min-height:68px!important;height:auto!important;background:var(--greenSoft)!important;border-color:var(--line)!important;font-size:15px!important;padding:12px 14px!important}.tile{transition:transform .15s ease,background .15s ease}.tile:active{transform:scale(.975)}.fp .card{transition:transform .18s ease,opacity .18s ease}.quizNudge{display:none!important}.quizSlide .card{justify-content:stretch}.quizTop{height:25px;padding:8px 15px 0;text-align:right;font-size:10px;color:var(--muted);letter-spacing:.05em}.quizBody{flex:1;display:flex;flex-direction:column;padding:22px 18px 18px;min-height:0}.quizPrompt{font-size:19px;font-weight:700;line-height:1.25}.quizHero{min-height:190px;display:grid;place-items:center;text-align:center}.quizHero.char{font-family:"Songti SC",serif;font-size:128px}.quizHero.word{font-size:38px;font-weight:760}.quizChoices{display:grid;grid-template-columns:1fr 1fr;gap:9px}.quizChoice{min-height:58px;border:1px solid var(--line);background:var(--paper);border-radius:10px;padding:9px 10px;font-size:15px;font-weight:650}.quizChoice.charChoice{font-family:"Songti SC",serif;font-size:34px}.quizChoice.correct{background:var(--greenSoft);color:var(--green)}.quizChoice.wrong{outline:2px solid #a64a36}.quizChoice.dim{opacity:.45}.quizFeedback{margin-top:12px;border-top:1px solid var(--line);padding-top:13px;display:none;align-items:center;gap:12px}.quizFeedback.on{display:flex}.feedbackChar{font-family:"Songti SC",serif;font-size:42px}.feedbackText b{display:block;font-size:17px}.feedbackText span{display:block;font-size:13px;color:var(--muted)}.quizHint{margin-top:auto;text-align:center;color:var(--muted);font-size:11px;padding-top:10px}
@media(max-height:820px){.family button{min-height:60px}.fh{font-size:33px}.stroke{min-height:56px!important}.quizHero{min-height:145px}.quizHero.char{font-size:104px}.quizHero.word{font-size:32px}}
`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
const tag=document.createElement('div');tag.className='buildTag';tag.textContent='v '+BUILD;document.body.appendChild(tag);
const ALT={
'一':[['我有一个朋友。','wǒ yǒu yí ge péngyou','I have a friend.'],['我想买一本书。','wǒ xiǎng mǎi yì běn shū','I want to buy a book.'],['一天有二十四个小时。','yì tiān yǒu èrshísì ge xiǎoshí','A day has 24 hours.']],
'人':[['这里人很多。','zhèlǐ rén hěn duō','There are many people here.'],['他是中国人。','tā shì Zhōngguó rén','He is Chinese.'],['我家有三个人。','wǒ jiā yǒu sān ge rén','There are three people in my family.']],
'大':[['北京很大。','Běijīng hěn dà','Beijing is very big.'],['这个房间不大。','zhège fángjiān bú dà','This room is not big.'],['她有一只大狗。','tā yǒu yì zhī dà gǒu','She has a big dog.']],
'小':[['这个房间很小。','zhège fángjiān hěn xiǎo','This room is small.'],['我有一个小问题。','wǒ yǒu yí ge xiǎo wèntí','I have a small question.'],['这只猫很小。','zhè zhī māo hěn xiǎo','This cat is small.']],
'我':[['我是学生。','wǒ shì xuésheng','I am a student.'],['我住在巴黎。','wǒ zhù zài Bālí','I live in Paris.'],['我喜欢喝茶。','wǒ xǐhuan hē chá','I like drinking tea.']],
'你':[['你好吗？','nǐ hǎo ma','How are you?'],['你叫什么名字？','nǐ jiào shénme míngzi','What is your name?'],['你住在哪儿？','nǐ zhù zài nǎr','Where do you live?']],
'好':[['今天天气很好。','jīntiān tiānqì hěn hǎo','The weather is very nice today.'],['这个很好吃。','zhège hěn hǎochī','This is delicious.'],['好，我们走吧。','hǎo, wǒmen zǒu ba','Okay, let’s go.']],
'是':[['他是老师。','tā shì lǎoshī','He is a teacher.'],['这是我的书。','zhè shì wǒ de shū','This is my book.'],['你是法国人吗？','nǐ shì Fǎguó rén ma','Are you French?']],
'不':[['我不喝咖啡。','wǒ bù hē kāfēi','I don’t drink coffee.'],['今天不冷。','jīntiān bù lěng','It is not cold today.'],['他不是老师。','tā bú shì lǎoshī','He is not a teacher.']],
'有':[['我有一个问题。','wǒ yǒu yí ge wèntí','I have a question.'],['你有时间吗？','nǐ yǒu shíjiān ma','Do you have time?'],['这里有很多人。','zhèlǐ yǒu hěn duō rén','There are many people here.']],
'在':[['我在家。','wǒ zài jiā','I am at home.'],['他在北京工作。','tā zài Běijīng gōngzuò','He works in Beijing.'],['书在桌子上。','shū zài zhuōzi shàng','The book is on the table.']],
'学':[['我在学汉语。','wǒ zài xué Hànyǔ','I am learning Chinese.'],['她在大学学习。','tā zài dàxué xuéxí','She studies at university.'],['我们一起学吧。','wǒmen yìqǐ xué ba','Let’s study together.']],
'吃':[['我们去吃饭吧。','wǒmen qù chīfàn ba','Let’s go eat.'],['你想吃什么？','nǐ xiǎng chī shénme','What do you want to eat?'],['我喜欢吃面。','wǒ xǐhuan chī miàn','I like eating noodles.']],
'喝':[['我想喝水。','wǒ xiǎng hē shuǐ','I want to drink water.'],['你喝茶吗？','nǐ hē chá ma','Do you drink tea?'],['她不喝咖啡。','tā bù hē kāfēi','She doesn’t drink coffee.']],
'看':[['我晚上看书。','wǒ wǎnshang kàn shū','I read in the evening.'],['你看这个。','nǐ kàn zhège','Look at this.'],['我们去看电影。','wǒmen qù kàn diànyǐng','Let’s go see a movie.']],
'说':[['你会说汉语吗？','nǐ huì shuō Hànyǔ ma','Can you speak Chinese?'],['他说得很快。','tā shuō de hěn kuài','He speaks very quickly.'],['请再说一次。','qǐng zài shuō yí cì','Please say it again.']],
'想':[['我想去中国。','wǒ xiǎng qù Zhōngguó','I want to go to China.'],['你想吃什么？','nǐ xiǎng chī shénme','What do you want to eat?'],['我想一想。','wǒ xiǎng yì xiǎng','Let me think.']],
'去':[['明天我去北京。','míngtiān wǒ qù Běijīng','Tomorrow I’m going to Beijing.'],['我们去哪儿？','wǒmen qù nǎr','Where are we going?'],['我去上班。','wǒ qù shàngbān','I’m going to work.']],
'来':[['你什么时候来？','nǐ shénme shíhou lái','When are you coming?'],['请进来。','qǐng jìnlái','Please come in.'],['他明天来巴黎。','tā míngtiān lái Bālí','He is coming to Paris tomorrow.']],
'水':[['请给我一杯水。','qǐng gěi wǒ yì bēi shuǐ','Please give me a glass of water.'],['我想喝水。','wǒ xiǎng hē shuǐ','I want to drink water.'],['这里的水很好喝。','zhèlǐ de shuǐ hěn hǎohē','The water here tastes good.']]
};
window.examples=c=>ALT[c.h]||[example(c)];
const oldPage=page;
window.page=function(c,i){const exs=examples(c),ex=exs[0],fam=(c.family||[]).filter(h=>byH[h]);return `<div class="fp" data-i="${i}" data-h="${c.h}"><div class="card"><div class="cHead">HSK 1 · ${c.index}/${ALL.length}</div><div class="heroChar"><div class="big">${c.h}</div><div class="py">${c.p}</div><div class="meaning">${c.contextMeaning}</div><button class="audio" data-speak>🔊</button></div><div class="learnBody"><div class="section"><div class="lab">Key context</div><div class="memory"><span class="hook">Remember</span> ${memory(c)}</div></div><div class="section"><div class="sentenceHead"><div class="lab">In a sentence</div>${exs.length>1?'<button class="sentenceNext" data-next-sentence aria-label="Another example">↻</button>':''}</div><div class="sentenceExample" data-sentence-index="0"><div class="exCn">${ex[0]}</div><div class="exPy">${ex[1]||''}</div><div class="exEn">${ex[2]||''}</div></div></div><div class="section"><div class="lab">Related shapes</div>${fam.length?`<div class="family">${fam.map(h=>{const r=byH[h];return `<button data-family="${h}"><span class="fh">${h}</span><span class="fpinyin">${r.p}</span><span class="fmeaning">${r.contextMeaning}</span></button>`}).join('')}</div>`:'<div class="none">Related forms will appear as you meet them.</div>'}</div><button class="stroke" data-stroke>Practice stroke order</button><div class="dots">${focusSet.map((_,j)=>j===i?'●':'○').join('')}</div></div></div></div>`};
function bindExtras(){document.querySelectorAll('.fp[data-h]').forEach(fp=>{const c=byH[fp.dataset.h];const s=fp.querySelector('[data-stroke]');if(s)s.onclick=e=>{e.preventDefault();e.stopPropagation();openStroke(c)};const n=fp.querySelector('[data-next-sentence]');if(n)n.onclick=e=>{e.preventDefault();e.stopPropagation();const list=examples(c),wrap=fp.querySelector('.sentenceExample'),idx=(Number(wrap.dataset.sentenceIndex||0)+1)%list.length,ex=list[idx];wrap.dataset.sentenceIndex=idx;wrap.querySelector('.exCn').textContent=ex[0];wrap.querySelector('.exPy').textContent=ex[1]||'';wrap.querySelector('.exEn').textContent=ex[2]||'';wrap.animate?.([{opacity:.45,transform:'translateY(3px)'},{opacity:1,transform:'none'}],{duration:170,easing:'ease-out'});n.animate?.([{transform:'rotate(0)'},{transform:'rotate(180deg)'}],{duration:220})};fp.querySelectorAll('[data-family]').forEach(b=>b.onclick=()=>openFocus([byH[b.dataset.family]],0))})}
const origOpen=openFocus;window.openFocus=function(set,start=0){const out=origOpen(set,start);requestAnimationFrame(()=>{bindExtras();setupQuizFlow()});return out};
let quizAdded=false,quizQs=[];
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}function mains(){return focusSet.slice(0,6).filter(Boolean)}
function makeQs(){return shuffle(mains()).slice(0,4).map((c,i)=>({c,type:i%2?'character':'meaning'}))}
function pool(c,n=3){return shuffle(ALL.filter(x=>x.h!==c.h&&x.contextMeaning!==c.contextMeaning)).slice(0,n)}
function quizHtml(q,i){const opts=shuffle([q.c,...pool(q.c)]),m=q.type==='meaning';return `<div class="fp quizSlide" data-quiz-index="${i}"><div class="card"><div class="quizTop">TEST · ${i+1}/4</div><div class="quizBody"><div class="quizPrompt">${m?'What does this character mean?':'How do you write this in Chinese?'}</div><div class="quizHero ${m?'char':'word'}">${m?q.c.h:q.c.contextMeaning}</div><div class="quizChoices">${opts.map(x=>`<button class="quizChoice ${m?'':'charChoice'}" data-choice="${x.h}" data-ok="${x.h===q.c.h}">${m?x.contextMeaning:x.h}</button>`).join('')}</div><div class="quizFeedback"><div class="feedbackChar">${q.c.h}</div><div class="feedbackText"><b>${q.c.p}</b><span>${q.c.contextMeaning}</span></div></div><div class="quizHint">Choose an answer</div></div></div></div>`}
function bindQuiz(){document.querySelectorAll('.quizSlide').forEach(sl=>{sl.querySelectorAll('[data-choice]').forEach(btn=>btn.onclick=e=>{e.preventDefault();if(sl.dataset.answered)return;sl.dataset.answered='1';const ok=btn.dataset.ok==='true',q=quizQs[Number(sl.dataset.quizIndex)];sl.querySelectorAll('[data-choice]').forEach(b=>{if(b.dataset.ok==='true')b.classList.add('correct');else if(b===btn)b.classList.add('wrong');else b.classList.add('dim')});sl.querySelector('.quizFeedback').classList.add('on');sl.querySelector('.quizHint').textContent=Number(sl.dataset.quizIndex)===quizQs.length-1?'Swipe either way for the next 6':'Swipe either way for the next question';let s=sk(q.c.h);state.seen[q.c.h]=1;s.exposures++;s.last=Date.now();if(ok){s.meaning=Math.min(5,(s.meaning||0)+1);s.recognition=Math.min(5,(s.recognition||0)+1)}else s.mistakes++;mastery(q.c);save();progress()});let x=0,y=0;sl.addEventListener('touchstart',e=>{if(e.touches[0]){x=e.touches[0].clientX;y=e.touches[0].clientY}},{passive:true});sl.addEventListener('touchend',e=>{if(!sl.dataset.answered||!e.changedTouches[0])return;const dx=e.changedTouches[0].clientX-x,dy=e.changedTouches[0].clientY-y;if(Math.abs(dx)<45||Math.abs(dx)<Math.abs(dy)*1.15)return;const qi=Number(sl.dataset.quizIndex),p=$('#pager');if(qi<quizQs.length-1)p.scrollTo({left:p.clientWidth*(focusSet.length+qi+1),behavior:'smooth'});else{closeFocus();nextBoard()}},{passive:true})})}
function setupQuizFlow(){quizAdded=false;quizQs=[];const p=$('#pager');if(!p||focusSet.length<6)return;const watch=()=>{const i=Math.round(p.scrollLeft/p.clientWidth);if(i===focusSet.length-1&&!quizAdded){quizAdded=true;quizQs=makeQs();p.insertAdjacentHTML('beforeend',quizQs.map(quizHtml).join(''));bindQuiz()}};p.addEventListener('scroll',watch,{passive:true});watch()}
setTimeout(()=>{bindExtras()},0);
})();